version: '3.8'

services:
  postgres:
    container_name: 'postgres'
    #image: 'postgres:13.1'
    image: 'postgres:12.5'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
